services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: escoligest
      POSTGRES_USER: escoligest
      POSTGRES_PASSWORD: escolitest
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_NAME=escoligest
      - DATABASE_USER=escoligest
      - DATABASE_PASSWORD=escolitest
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    depends_on:
      - db

volumes:
  pgdata:
