# Generated by Django 5.2.7 on 2025-11-06 16:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_default_calendar_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientactivity',
            name='recurrence',
            field=models.CharField(choices=[('NONE', 'Una vez'), ('DAILY', 'Diaria'), ('WEEKLY', 'Semanal'), ('MONTHLY', 'Mensual')], default='NONE', max_length=10),
        ),
        migrations.CreateModel(
            name='PatientActivityCompletion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('occurrence_date', models.DateField()),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='appointments.patientactivity')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurrence_date', '-completed_at'],
                'unique_together': {('activity', 'occurrence_date')},
            },
        ),
    ]
