# Generated by Django 5.2.7 on 2025-11-13 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_alter_patientactivity_recurrence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientactivity',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
