# Generated by Django 5.2.7 on 2025-11-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='articles/pdfs/'),
        ),
    ]
