# Generated by Django 5.2.7 on 2025-11-07 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreusers', '0004_dedupe_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
